apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/hybrid-cloud-team/my-ecr-obs.git'
    targetRevision: HEAD
    path: obs/monitoring/prometheus
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false
      - Replace=true

  # ğŸ”´ [í•µì‹¬ ì¶”ê°€] Helm admission hook ë¦¬ì†ŒìŠ¤ Argo ê´€ë¦¬ ëŒ€ìƒì—ì„œ ì œì™¸
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: prometheus-stack-kube-prom-admission

    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: prometheus-stack-kube-prom-admission

    - group: rbac.authorization.k8s.io
      kind: Role
      name: prometheus-stack-kube-prom-admission
      namespace: monitoring

    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: prometheus-stack-kube-prom-admission
      namespace: monitoring

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: prometheus-stack-kube-prom-admission

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: prometheus-stack-kube-prom-admission
