apiVersion: v2
name: my-prometheus-wrapper
description: Wrapper chart for Prometheus Stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 61.3.0  # 호환성이 좋은 최신 버전 중 하나입니다
    repository: https://prometheus-community.github.io/helm-charts
