apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
spec:
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
      - name: vm-storage
        image: victoriametrics/victoria-metrics:v1.101.0
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: data
          mountPath: /storage
      # S3로 백업을 보내는 사이드카 일꾼
      - name: vmbackup
        image: victoriametrics/vmbackup:v1.101.0
        args:
        - -storageDataPath=/storage
        - -dst=s3://thanos-storage-cluster-01/vm-backup
        - -aws.region=us-east-1
        - -snapshot.createInterval=1h
        volumeMounts:
        - name: data
          mountPath: /storage
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vm-pvc # PVC가 미리 생성되어 있어야 합니다.
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
spec:
  ports:
  - port: 8428
    targetPort: 8428
  selector:
    app: victoria-metrics
