# victoria-metrics-new.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-server-test  # 이름을 아예 바꿉니다.
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-server-test
  template:
    metadata:
      labels:
        app: vm-server-test
    spec:
      containers:
      - name: vm-storage
        image: victoriametrics/victoria-metrics:v1.101.0
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: storage-temp
          mountPath: /storage
      - name: vmbackup
        image: victoriametrics/vmbackup:v1.101.0
        args:
        - -storageDataPath=/storage
        - -dst=s3://my-victoria-storage-01/vm-backup
        - -aws.region=us-east-1
        - -snapshot.createInterval=1h
        volumeMounts:
        - name: storage-temp
          mountPath: /storage
      volumes:
      - name: storage-temp
        emptyDir: {}  # 디스크 없이 무조건 띄우기
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics  # Prometheus가 찾는 이름은 그대로 유지
  namespace: default
spec:
  ports:
  - port: 8428
    targetPort: 8428
  selector:
    app: vm-server-test
