apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-server  # 이름을 바꿔서 새로운 서비스인 것처럼 인식시킵니다.
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-server
  template:
    metadata:
      labels:
        app: vm-server
    spec:
      containers:
      - name: vm-storage
        image: victoriametrics/victoria-metrics:v1.101.0
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: temp-storage
          mountPath: /storage
      - name: vmbackup
        image: victoriametrics/vmbackup:v1.101.0
        args:
        - -storageDataPath=/storage
        - -dst=s3://my-victoria-storage-01/vm-backup  # <-- 생성하신 S3 버킷명 입력
        - -aws.region=us-east-1
        - -snapshot.createInterval=1h
        volumeMounts:
        - name: temp-storage
          mountPath: /storage
      volumes:
      - name: temp-storage
        emptyDir: {}  # PVC 없이 노드 로컬 공간을 사용함
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics  # Prometheus가 데이터를 쏠 주소는 그대로 유지
  namespace: default
spec:
  ports:
  - port: 8428
    targetPort: 8428
  selector:
    app: vm-server
