apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
      - name: vm-storage
        image: victoriametrics/victoria-metrics:v1.101.0
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: data
          mountPath: /storage
      - name: vmbackup
        image: victoriametrics/vmbackup:v1.101.0
        args:
        - -storageDataPath=/storage
        - -dst=s3://my-victoria-storage-01/vm-backup
        - -aws.region=us-east-1
        - -snapshot.createInterval=1h
        volumeMounts:
        - name: data
          mountPath: /storage
      volumes:
      - name: data
        emptyDir: {} # PVC 대신 이걸 써야 무조건 뜹니다!
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: default
spec:
  ports:
  - port: 8428
    targetPort: 8428
  selector:
    app: victoria-metrics
