apiVersion: v2
name: my-grafana-wrapper
description: Wrapper chart for Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    version: 8.5.1  # 사용하고 싶은 공식 Grafana 차트 버전을 적으세요
    repository: https://grafana.github.io/helm-charts
