apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  namespace: monitoring
spec:
  serviceName: thanos-store
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store  # 1. 이 셀렉터와
  template:
    metadata:
      labels:
        app: thanos-store  # 2. 이 라벨이 반드시 같아야 에러가 안 납니다
    spec:
      serviceAccountName: thanos-query-sa # IAM Role(ARN) 연결
      containers:
        - name: thanos-store
          image: quay.io/thanos/thanos:v0.37.2
          args:
            - store
            - --objstore.config-file=/etc/thanos/objstore.yml
            - --data-dir=/var/thanos/store
          ports:
            - name: grpc
              containerPort: 10901
          volumeMounts:
            - name: objstore-config
              mountPath: /etc/thanos
      volumes:
        - name: objstore-config
          secret:
            secretName: thanos-objstore-config
